### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jonathanvx** [svart-ravn/mysql_udf#1]
Does this not need a goup_deinit() ?

"De-initialize the function and clean up memory usage. It is called after the statement that used the UDF name."

Something like this:
https://blog.golang.org/c-go-cgo
C.free(result)

Or is that handled by Go?

**Comment by svart-ravn** [comment]
golang has GC.
if you are in doubt you can always try to use valgrind to detect memory leaks

valgrind --leak-check=full -v <your_program>

**Comment by jonathanvx** [comment]
I appreciate that Go had GC, but I believe the regular C code that Go translates into and the MySQL system itself expects a _deinit for each UDF. Its in the book "MySQL 5.1 Plugin Development".

**Comment by svart-ravn** [comment]
I was wrong, thanks for pointing on it.

here is how usually deinit function looks like:

`void  <function_name>_deinit(UDF_INIT *initid)`

while in goup we do not need to store temporary data to access it in main/add/reset methods (for example in aggregated functions) we do not need to have deinit method because there is nothing to free (because we did not allocate anything in init).
